v0.1.2 test tools

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,13 +1,21 @@
 ---
 name: Arduino Library CI
 
-on: [pull_request, push, repository_dispatch]
+on:
+  push:
+    branches:
+      - "**"       # 普通分支推送时运行代码检查
+    tags:
+      - "v*.*.*"   # 小写 v 触发
+      - "V*.*.*"   # 大写 V 触发
+  pull_request:
+  repository_dispatch:
 
 permissions:
   contents: read
 
 env:
-  PYTHON_3: "3.11"
+  PYTHON_3: "3.11.13"
   REQUIREMENTS_PATH: './.github/config/requirements.txt' ## 依赖文件路径
 
 jobs:
@@ -37,11 +45,13 @@ jobs:
         with:
           path: venv                            ## 缓存路径
           key: ${{ runner.os }}-${{ env.PYTHON_3 }}-venv-${{ steps.cache-key.outputs.key }}
+
       - name: Create Python virtual environment ## 创建 Python 虚拟环境
         run: |
           python -m venv venv
           . venv/bin/activate
           pip install -r ${{ env.REQUIREMENTS_PATH }}
+
       - name: Save venv to cache
         if: steps.cache-venv.outputs.cache-hit != 'true'
         uses: actions/cache@v4.2.4
@@ -50,7 +60,11 @@ jobs:
           key: ${{ runner.os }}-${{ env.PYTHON_3 }}-venv-${{ steps.cache-key.outputs.key }}
 
   pylint:
-    name: check pylint
+    if: >
+      (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/'))
+      || github.event_name == 'pull_request'
+      || github.event_name == 'repository_dispatch'
+
     runs-on: ubuntu-24.04
     continue-on-error: true
     needs:
@@ -77,7 +91,7 @@ jobs:
             exit 0
           fi
 
-          pylint  -f parseable --rcfile=./.github/config/.pylintrc --persistent=n $FILES # python/raspberrypi    ##运行 pylint 检查代码规范
+          pylint  -f parseable --rcfile=./.github/config/.pylintrc --persistent=n $FILES || true  ##运行 pylint 检查代码规范
         if: always()
       - name: Suggested changes
         run: |
@@ -91,6 +105,11 @@ jobs:
         if: always()
 
   clang-tidy:
+    if: >
+      (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/'))
+      || github.event_name == 'pull_request'
+      || github.event_name == 'repository_dispatch'
+
     name: check clang-tidy and build
     runs-on: ubuntu-24.04
     needs:
@@ -105,61 +124,92 @@ jobs:
           python-version: ${{ env.PYTHON_3 }}
           cache-key: ${{ needs.common.outputs.cache-key }}
 
+
       - name: Install PlatformIO
-        run: pip install platformio
+        run: |
+          pip install platformio
+          cp ./.github/config/platformio.ini .
 
       - name: Generate compile_commands.json
         run: |
-          pio run -t compiledb --project-dir ./.github/config/
+          pio run -t compiledb
 
       - name: Run clang-tidy
         run: |
-          export C_INCLUDE_PATH="$PWD/src:$PWD/examples" ## 设置 include 路径
-          export CPLUS_INCLUDE_PATH="$PWD/src:$PWD/examples" ## 设置 include 路径
+          FILES=$(find . \
+          -path './.git'    -prune -o \
+          -path './.github' -prune -o \
+          -type f \( -name '*.cpp' -o -name '*.h' -o -name '*.ino' \) -print)
 
-          FILES=$(find . -type f \( -name '*.cpp' -o -name '*.h' -o -name '*.ino' \))
           echo "Running clang-tidy on $FILES"
-          if [ -z "$FILES" ]; then
+          if [ -z "$FILES" ]; then             # 检查是否有文件
               echo "No source files found."
               exit 0
           fi
-          # clang-tidy $FILES -p ./.github/config/  -header-filter="." -config-file=./.github/config/.clang-tidy -system-headers=false
-
-          for file in $FILES; do
-            echo "Processing $file"
-            clang-tidy "$file" -p .github/config/ \
-              -header-filter="$filter" \
-              -config-file=./.github/config/.clang-tidy \
-              --extra-arg="-I$PWD/src" \
-              --extra-arg="-I$PWD/examples" \
-              --extra-arg=-Wno-notes \
-              --quiet \
-              || true
-          done
+          clang-tidy $FILES -p . \
+          -header-filter="$filter" \
+          -config-file=./.github/config/.clang-tidy \
+          || false
         if: always()
 
 
-  # pre-commit:
-  #   name: check pre-commit
-  #   runs-on: ubuntu-24.04
-  #   continue-on-error: true   ## pylint 出错不会让 workflow fail
-  #   needs:
-  #     - common                      ## 依赖 common job，确保环境变量已设置
-  #   steps:
-  #     - name: Check out code from GitHub
-  #       uses: actions/checkout@v5.0.0
-  #     - name: Restore Python 3
-  #       uses: ./.github/actions
-  #       with:
-  #         python-version: ${{ env.PYTHON_3 }}
-  #         cache-key: ${{ needs.common.outputs.cache-key }}
+  release:
+      name: Check tag version
+      if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/V')
+      runs-on: ubuntu-24.04
+      permissions:
+        contents: write
+      needs: common
+      concurrency:
+        group: release-${{ github.ref }}
+        cancel-in-progress: true
+      steps:
+        - name: Checkout code
+          uses: actions/checkout@v5.0.0
+          with:
+            fetch-depth: 0
 
-  #     - uses: pre-commit/action@v3.0.1 ## 使用 pre-commit action 来运行 pre-commit 检查
-  #       env:
-  #         SKIP: pylint
-  #     - uses: pre-commit-ci/lite-action@v1.1.0
-  #       if: always()
+        - name: Verify library.properties version
+          id: verify
+          run: |
+            RAW_TAG="${GITHUB_REF#refs/tags/}"      # 例如 v1.0.1 或 V1.0.1
+            TAG_VERSION="${RAW_TAG#[vV]}"           # 去掉前导 v 或 V -> 1.0.1
 
+            # 读取并清理文件里的 version= 值
+            if [ ! -f library.properties ]; then
+              echo "❌ library.properties not found"
+              exit 1
+            fi
+            FILE_VERSION="$(awk -F= '/^[[:space:]]*version[[:space:]]*=/ {print $2; exit}' library.properties \
+              | tr -d '\r' | xargs)"
+            echo "📦 Tag version: $TAG_VERSION"
+            echo "🧾 File version: $FILE_VERSION"
+
+            if [ "$TAG_VERSION" != "$FILE_VERSION" ]; then
+              echo "❌ Version mismatch!"
+              echo "library.properties version ($FILE_VERSION) does not match tag ($TAG_VERSION)"
+              exit 1
+            fi
+
+            echo "✅ Version match confirmed: $TAG_VERSION"
+            echo "tag_version=$TAG_VERSION" >> $GITHUB_OUTPUT
+
+        # - name: Create release zip
+        #   id: zip
+        #   run: |
+        #     ZIP_NAME="${{ github.event.repository.name }}_${{ steps.verify.outputs.tag_version }}.zip"
+        #     echo "Creating $ZIP_NAME"
+        #     zip -r "$ZIP_NAME" . \
+        #       -x '*.git*' '.github/*' '__pycache__/*' # 排除不必要的文件 .github  、.git  、__pycache__
+        #     echo "zip_name=$ZIP_NAME" >> $GITHUB_OUTPUT
+
+        # - name: Upload GitHub Release
+        #   uses: softprops/action-gh-release@v2
+        #   with:
+        #     files: ${{ steps.zip.outputs.zip_name }}
+        #     generate_release_notes: true
+        #   env:
+        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   ci-status:
     runs-on: ubuntu-24.04
@@ -167,6 +217,14 @@ jobs:
       - common
       - pylint
       - clang-tidy
+      - release
     if: always()
     steps:
-      - run: echo "Running ci-status job"
+      - name: Print job results
+        run: |
+          echo "==== CI Summary ===="
+          echo "common:     ${{ needs.common.result }}"
+          echo "pylint:     ${{ needs.pylint.result }}"
+          echo "clang-tidy: ${{ needs['clang-tidy'].result }}"
+          echo "release:    ${{ needs.release.result }}"
+          echo "===================="
